apiVersion: v1
kind: Service
metadata:
  name: isinv-front-service
  namespace: isinv
spec:
  selector:
    app: isinv-front
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
